[build]
  publish = "WEBSITE/dist"

# Redirect assets directly from Framer
[[redirects]]
  from = "/assets/*"
  to = "https://empathic-curiosity-142704.framer.app/assets/:splat"
  status = 200
  force = true

# Allow direct access to static files
[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200


[[redirects]]
  from = "/*.ttf"
  to = "https://acceso-integration.onrender.com/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# /map rules
[[redirects]]
  from = "/map"
  to = "https://acceso-integration.onrender.com/"
  status = 200
  force = true
  headers = {X-Forwarded-Host = "acceso.edoardograci.com"}

[[redirects]]
  from = "/map/*"
  to = "https://acceso-integration.onrender.com/:splat"
  status = 200
  force = true
  headers = {X-Forwarded-Host = "acceso.edoardograci.com"}

# CATCH-ALL RULE MUST BE LAST
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/framer-proxy/:splat"
  status = 200
  force = true

