[build]
  publish = "WEBSITE/dist"

# Redirect assets directly from Framer
[[redirects]]
  from = "/assets/*"
  to = "https://empathic-curiosity-142704.framer.app/assets/:splat"
  status = 200
  force = true

# Allow direct access to static files
[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/map/*"
  to = "https://acceso-integration.onrender.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/map"
  to = "https://acceso-integration.onrender.com/"
  status = 200
  force = true

# Route everything through the function without changing the URL
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/framer-proxy/:splat"
  status = 200
  force = true

