[build]
  publish = "WEBSITE/dist"

# Redirect assets directly from Framer
[[redirects]]
  from = "/assets/*"
  to = "https://empathic-curiosity-142704.framer.app/assets/:splat"
  status = 200
  force = true

# Allow direct access to static files
[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

# Fix font request - redirect root font request to integration site
[[redirects]]
  from = "/PPSupplySans-Variable.ttf"
  to = "https://acceso-integration.onrender.com/PPSupplySans-Variable.ttf"
  status = 200
  force = true

# Handle font requests that come through /map path
[[redirects]]
  from = "/map/PPSupplySans-Variable.ttf"
  to = "https://acceso-integration.onrender.com/PPSupplySans-Variable.ttf"
  status = 200
  force = true

# General font file patterns
[[redirects]]
  from = "/*.ttf"
  to = "https://acceso-integration.onrender.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*.woff"
  to = "https://acceso-integration.onrender.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*.woff2"
  to = "https://acceso-integration.onrender.com/:splat"
  status = 200
  force = true

# Reverse proxy for /map (more specific rules first)
[[redirects]]
  from = "/map/*"
  to = "https://acceso-integration.onrender.com/:splat"
  status = 200
  force = true
  headers = {X-Forwarded-Host = "acceso.edoardograci.com"}

[[redirects]]
  from = "/map"
  to = "https://acceso-integration.onrender.com/"
  status = 200
  force = true
  headers = {X-Forwarded-Host = "acceso.edoardograci.com"}

# Route everything through the function without changing the URL (LAST)
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/framer-proxy/:splat"
  status = 200
  force = true
