[build]
  publish = "WEBSITE/dist"

# Redirect assets directly from Framer
[[redirects]]
  from = "/assets/*"
  to = "https://empathic-curiosity-142704.framer.app/assets/:splat"
  status = 200
  force = true

# Allow direct access to static files
[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

# FONT RULES FIRST - BEFORE /map/* rules - WITH CORS HEADERS
[[redirects]]
  from = "/PPSupplySans-Variable.ttf"
  to = "https://acceso-integration.onrender.com/PPSupplySans-Variable.ttf"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/map/PPSupplySans-Variable.ttf"
  to = "https://acceso-integration.onrender.com/PPSupplySans-Variable.ttf"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# General font patterns BEFORE /map/* - WITH CORS HEADERS
[[redirects]]
  from = "/*.ttf"
  to = "https://acceso-integration.onrender.com/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/*.woff"
  to = "https://acceso-integration.onrender.com/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/*.woff2"
  to = "https://acceso-integration.onrender.com/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# NOW the /map rules (AFTER font rules)
[[redirects]]
  from = "/map"
  to = "https://acceso-integration.onrender.com/"
  status = 200
  force = true
  headers = {X-Forwarded-Host = "acceso.edoardograci.com"}

[[redirects]]
  from = "/map/*"
  to = "https://acceso-integration.onrender.com/:splat"
  status = 200
  force = true
  headers = {X-Forwarded-Host = "acceso.edoardograci.com"}

# Route everything through the function without changing the URL (LAST)
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/framer-proxy/:splat"
  status = 200
  force = true
